version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/docker-ecr/
hooks:
  DockerStop:
    - location: script/application-stop.sh
      timeout: 60
      runas: root
  DockerPull:
    - location: script/after-install.sh
      timeout: 60
      runas: root
  DockerStart:
    - location: script/application-start.sh
      timeout: 60
      runas: root
